#theme: jekyll-theme-dinky
#theme: just-the-docs
title: HDRUK-Turing PhD Programme in Health Data Science
description: PhD Programme Student Handbook
logo: images/hdruk-logo.png
remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2020 Christopher Yau. Distributed by an <a href=\"https://github.com/cwcyau/hdruk-phd-handbook/blob/master/LICENSE\">GNU GPL-3.0.</a>"